################################################################################
# AdGuard Home Configuration File
# 
# This is a pre-configured template that binds to 0.0.0.0 (all interfaces).
# This solves the issue where the web interface setup wizard doesn't allow
# selecting 0.0.0.0 during initial configuration.
#
# USAGE:
# 1. This file will be automatically used when AdGuard Home starts
# 2. On first start, navigate to http://YOUR-SERVER-IP:3000
# 3. Complete the initial setup wizard with these credentials:
#    - Create your admin username and password
#    - The binding is already configured to 0.0.0.0
# 4. After setup, you can manage settings via the web interface
################################################################################

# Bind host for the admin web interface
# 0.0.0.0 means bind to all network interfaces, making it accessible from:
# - The local machine (127.0.0.1)
# - Docker container network (172.20.0.x)
# - Your LAN network (192.168.x.x)
bind_host: 0.0.0.0
bind_port: 3000

# Users configuration (will be set during first-time setup)
users: []

# Authentication settings
auth_attempts: 5
block_auth_min: 15

# HTTP server settings
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h

# DNS server configuration
dns:
  # Bind to all interfaces for DNS queries
  bind_hosts:
    - 0.0.0.0
  port: 53
  
  # Anonymous statistics
  anonymize_client_ip: false
  
  # Protection settings
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  
  # Filtering settings
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  
  # Rate limiting
  ratelimit: 20
  ratelimit_whitelist: []
  
  # DNS cache settings
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  
  # Upstream DNS servers (Cloudflare and Google)
  upstream_dns:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
  
  upstream_dns_file: ""
  bootstrap_dns:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
  
  # DNS query settings
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  
  # DNS-over-HTTPS/TLS/QUIC settings
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  
  # EDNS Client Subnet
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  
  # Filtering mode
  filtering_enabled: true
  filters_update_interval: 24
  
  # Parental control
  parental_enabled: false
  
  # Safe browsing
  safebrowsing_enabled: false
  
  # Safe search
  safesearch_enabled: false
  
  # Maximum number of parallel requests
  max_goroutines: 300
  
  # IPSET configuration
  ipset: []
  ipset_file: ""
  
  # Handle PTR requests
  resolve_clients: true
  
  # Local PTR resolving
  local_ptr_upstreams: []
  
  # Serve plain DNS on additional ports
  upstream_mode: load_balance
  
  # Use private reverse DNS resolvers
  use_private_ptr_resolvers: true
  
  # Serve DNS on additional ports
  local_domain_name: lan

# TLS configuration (for DNS-over-TLS and DNS-over-HTTPS)
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false

# Filtering settings
filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2

# Whitelist filters
whitelist_filters: []

# User rules
user_rules: []

# DHCP server settings (disabled by default)
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false

# Client settings
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []

# Log configuration
log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false

# Operating system configuration
os:
  group: ""
  user: ""
  rlimit_nofile: 0

# Schema version
schema_version: 20

################################################################################
# Post-Setup Configuration
#
# After completing the initial setup wizard, you can:
# 1. Add more DNS blocklists via Filters → DNS blocklists
# 2. Configure DNS rewrites for Lancache via Filters → DNS rewrites
# 3. Adjust upstream DNS servers via Settings → DNS settings
# 4. Configure client settings and custom filtering rules
#
# Recommended additional blocklists:
# - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt
# - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt
# - https://blocklistproject.github.io/Lists/ads.txt
#
# For Lancache integration, add DNS rewrites in the web interface:
# - *.steamcontent.com → 192.168.8.2 (or your server IP)
# - *.download.epicgames.com → 192.168.8.2
# - *.origin.com → 192.168.8.2
# - And others as documented in the main README
################################################################################
