<?php
$CONFIG = array (
  'instanceid' => 'oc123456789',
  'passwordsalt' => 'generatedrandomsalt',
  'secret' => 'generatedrandomsecret',
  'trusted_domains' => array (
    0 => 'localhost',
    1 => '192.168.8.100',
    2 => '10.0.0.100',
    3 => 'nextcloud.local',
  ),
  'datadirectory' => '/mnt/nas-storage/data',
  'dbtype' => 'mysql',
  'version' => '27.1.3.1',
  'overwrite.cli.url' => 'http://192.168.8.100:8081',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'secure_password_here',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'enable_previews' => true,
  'preview_max_x' => 1024,
  'preview_max_y' => 1024,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => array (
    'OC\\Preview\\PNG',
    'OC\\Preview\\JPEG',
    'OC\\Preview\\GIF',
    'OC\\Preview\\BMP',
    'OC\\Preview\\XBitmap',
    'OC\\Preview\\MP3',
    'OC\\Preview\\TXT',
    'OC\\Preview\\MarkDown',
    'OC\\Preview\\PDF',
  ),
  'filesystem_check_changes' => 0,
  'part_file_in_storage' => false,
  'tempdirectory' => '/tmp',
  'log_type' => 'file',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'log_rotate_size' => 104857600,
  'apps_paths' => array (
    0 => array (
      'path' => '/var/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => array (
      'path' => '/var/www/nextcloud/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'default_phone_region' => 'US',
  'trashbin_retention_obligation' => 'auto, 30',
  'versions_retention_obligation' => 'auto, 365',
  'activity_expire_days' => 365,
  'simpleSignUpLink.shown' => false,
  'share_folder' => '/Shares',
  'skeletondirectory' => '',
  'default_language' => 'en',
  'default_locale' => 'en_US',
  'knowledgebaseenabled' => false,
  'allow_user_to_change_display_name' => false,
  'remember_login_cookie_lifetime' => 60*60*24*15,
  'session_lifetime' => 60 * 60 * 24,
  'session_keepalive' => true,
  'auto_logout' => false,
  'token_auth_enforced' => false,
  'auth.bruteforce.protection.enabled' => true,
  'ratelimit.protection.enabled' => true,
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'example.com',
  'mail_smtphost' => 'smtp.example.com',
  'mail_smtpport' => 587,
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'tls',
  'mail_smtpname' => 'nextcloud@example.com',
  'mail_smtppassword' => 'smtp_password_here',
);
